# Agent Engine Configuration with Profiles
default:
  display_name: "gcpcost_advisor-0.3.1"
  description: "Analyze the cost of GCP project and provide cost-saving advice.(gemini-2.5-pro)"
  gcs_dir_name: "gcpcost_advisor/0.3.1"

  # Agent configuration
  agent_engine:
    # Use instance_path to reference an existing agent instance
    instance_path: "gcpcost.agent.root_agent"

  # Environment variables
  env_vars:
    GCPCOST_TABLE: "dena-ai-sandbox-03-gcp.dena_ai_sandbox_03_gcp.costs"
    SLACK_WEBHOOK_URL:
      secret: "slack-webhook-url"
      version: "latest"

  # Package requirements
  requirements:
    - "google-cloud-aiplatform[adk,agent_engines]==1.96.0"
    - "google-adk"
    - "slackweb"
    - "gcpcost-0.3.1-py3-none-any.whl"

  extra_packages:
    - "gcpcost-0.3.1-py3-none-any.whl"

development:
  display_name: "gcpcost_advisor-dev"
  description: "Development version of GCP cost advisor"
  gcs_dir_name: "gcpcost_advisor/dev"

  agent_engine:
    instance_path: "gcpcost.agent.root_agent"

  env_vars:
    GCPCOST_TABLE: "dev-project.dataset.costs"
    SLACK_WEBHOOK_URL:
      secret: "dev-slack-webhook-url"
      version: "latest"

  requirements:
    - "google-cloud-aiplatform[adk,agent_engines]==1.96.0"
    - "google-adk"
    - "slackweb"
    - "gcpcost-0.3.1-py3-none-any.whl"

  extra_packages:
    - "gcpcost-0.3.1-py3-none-any.whl"

production:
  display_name: "gcpcost_advisor-prod"
  description: "Production version of GCP cost advisor"
  gcs_dir_name: "gcpcost_advisor/prod"

  agent_engine:
    instance_path: "gcpcost.agent.root_agent"

  env_vars:
    GCPCOST_TABLE: "prod-project.dataset.costs"
    SLACK_WEBHOOK_URL:
      secret: "prod-slack-webhook-url"
      version: "latest"

  requirements:
    - "google-cloud-aiplatform[adk,agent_engines]==1.96.0"
    - "google-adk"
    - "slackweb"
    - "gcpcost-0.3.1-py3-none-any.whl"

  extra_packages:
    - "gcpcost-0.3.1-py3-none-any.whl"
