# Agent Engine Configuration with Profiles
default:
  # Vertex AI Configuration
  vertex_ai:
    project: "dena-ai-sandbox-03-gcp"
    location: "us-central1"
    staging_bucket: "dena-ai-sandbox-03-gcp-staging"

  display_name: "gcpcost_advisor-0.3.1"
  description: "Analyze the cost of GCP project and provide cost-saving advice.(gemini-2.5-pro)"
  gcs_dir_name: "gcpcost_advisor/0.3.1"

  # Agent configuration
  agent_engine:
    # Use instance_path to reference an existing agent instance
    instance_path: "gcpcost.agent.root_agent"

  # Environment variables
  env_vars:
    GCPCOST_TABLE: "dena-ai-sandbox-03-gcp.dena_ai_sandbox_03_gcp.costs"
    SLACK_WEBHOOK_URL:
      secret: "slack-webhook-url"
      version: "latest"

  # Package requirements
  requirements:
    - "google-cloud-aiplatform[adk,agent_engines]==1.96.0"
    - "google-adk"
    - "slackweb"
    - "gcpcost-0.3.1-py3-none-any.whl"

  extra_packages:
    - "gcpcost-0.3.1-py3-none-any.whl"
